### ISSUE TITLE
Cannot download agent

### ISSUE THREAD

**Issue by maffelbaffel** [dmitry-zhuravlev/hotswap-agent-intellij-plugin#14]
Currently downloading the agent.jar doesnt work.
````
java.io.IOException: Cannot download 'https://github.com/HotswapProjects/HotswapAgent/releases/download/1.2.0/hotswap-agent-1.2.0.jar': Status: 404
com.hotswap.agent.plugin.services.DownloadManagerException: java.io.IOException: Cannot download 'https://github.com/HotswapProjects/HotswapAgent/releases/download/1.2.0/hotswap-agent-1.2.0.jar': Status: 404
	at com.hotswap.agent.plugin.services.DownloadManager$downloadAgentJarAsynchronously$1$downloadTask$1.run(DownloadManager.kt:80)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:713)
````

I guess the reason is, the name of the current HotswapAgent Release is RELEASE-1.2.0.
So the correct link would be:
https://github.com/HotswapProjects/HotswapAgent/releases/download/RELEASE-1.2.0/hotswap-agent-1.2.0.jar

**Comment by Pima-Dev** [comment]
Same problem for me.

**Comment by Plasticable** [comment]
Same.

**Comment by dmitry-zhuravlev** [comment]
Thanks to all for point to this issue!

 Fixed and deployed to plugin repository. 
Will be available after some moderation from JetBrains.

**Comment by rnentjes** [comment]
Now it's looking for 1.2.1-SNAPSHOT which also doesn't exists:

    java.io.IOException: Cannot download 'https://github.com/HotswapProjects/HotswapAgent/releases/download/1.2.1-SNAPSHOT/hotswap-agent-1.2.0.jar': Status: 404
