### ISSUE TITLE
Enable/Disable some of the hotswap agent plugins

### ISSUE THREAD

**Issue by kh0ma** [dmitry-zhuravlev/hotswap-agent-intellij-plugin#21]
Sometimes people have a problem with some of the hotswap agent plugins.
Such as here https://github.com/HotswapProjects/HotswapAgent/issues/187

It will be great to have a possibility to disable some of the hotswap agent plugins through the hotswap IntelliJ idea plugin.

**Comment by dmitry-zhuravlev** [comment]
@kh0ma Thank you for suggestion! The option will be added soon.
