### ISSUE TITLE
Upload plugin to JetBrains repo

### ISSUE THREAD

**Issue by edudant** [dmitry-zhuravlev/hotswap-agent-intellij-plugin#5]
Hi, is it possible to upload the plugin into [JetBrains repo](https://plugins.jetbrains.com/)?

**Comment by dmitry-zhuravlev** [comment]
@edudant it is already [there](https://plugins.jetbrains.com/plugin/9552-hotswapagent)

**Comment by edudant** [comment]
Great. However, the only way how to find it is to search for "HotSwapAgent". If you try "hotswap" or even "hotswap agent", it only finds "DCEVM integration" plugin.

The solution can be to use keywords "hotswap", "agent", "dcevm", "class redefinition" in plugin description.

**Comment by dmitry-zhuravlev** [comment]
You are right, discription will be updated accordingly.
